### ISSUE TITLE
[BUG] CLI fails when passing a --subset_max_train smaller than the data

### ISSUE THREAD

**Issue by jspaezp** [wfondrie/mokapot#38]
**Describe the bug:**

Using `--subset_max_train` on the CLI when the number of peptides is less than the provided number makes the command fail 

**To Reproduce:**

```
mokapot --subset_max_train 2000000 {SMALL_PIN_FILE}
```

```
mokapot --subset_max_train 5000000  --verbosity 2 -r SMALL_PIN.pin
[INFO] mokapot version 0.7.3
[INFO] Written by William E. Fondrie (wfondrie@uw.edu) in the
[INFO] Department of Genome Sciences at the University of Washington.
[INFO] Command issued:
[INFO] {MOKAPOT_PATH}/mokapot --subset_max_train 5000000 --verbosity 2 -r SMALL_PIN.pin
[INFO] 
[INFO] Starting Analysis
[INFO] =================
[INFO] Parsing PSMs...
[INFO] Reading SMALL_PIN.pin...
[INFO] Using 21 features:
[INFO]   (1)	lnrSp
[INFO]   (2)	deltLCn
[INFO]   (3)	deltCn
[INFO]   (4)	lnExpect
[INFO]   (5)	Xcorr
[INFO]   (6)	Sp
[INFO]   (7)	IonFrac
[INFO]   (8)	Mass
[INFO]   (9)	PepLen
[INFO]   (10)	Charge1
[INFO]   (11)	Charge2
[INFO]   (12)	Charge3
[INFO]   (13)	Charge4
[INFO]   (14)	Charge5
[INFO]   (15)	Charge6
[INFO]   (16)	enzN
[INFO]   (17)	enzC
[INFO]   (18)	enzInt
[INFO]   (19)	lnNumSP
[INFO]   (20)	dM
[INFO]   (21)	absdM
[INFO] Found 191131 PSMs.
[INFO]   - 113449 target PSMs and 77682 decoy PSMs detected.
[INFO] Splitting PSMs into 3 folds...
[INFO] 
[INFO] === Analyzing Fold 1 ===
Traceback (most recent call last):
  File "{MOKAPOT_PATH}/mokapot", line 8, in <module>
    sys.exit(main())
  File "{MOKAPOT_PATH}/mokapot/mokapot.py", line 94, in main
    psms, models = brew(
  File "{MOKAPOT_PATH}/mokapot/brew.py", line 102, in brew
    models = list(map_fun(*map_args))
  File "{MOKAPOT_PATH}/mokapot/brew.py", line 258, in _fit_model
    model.fit(train_set)
  File "{MOKAPOT_PATH}/mokapot/model.py", line 269, in fit
    subset_idx = np.random.choice(
  File "mtrand.pyx", line 965, in numpy.random.mtrand.RandomState.choice
ValueError: Cannot take a larger sample than population when 'replace=False'
```

**Expected Results**

Have the program warn that the passed --subset_max_train is smaller than the current number and have it run as if nothing was passed.

**Comment by jspaezp** [comment]
@wfondrie lmk what you think

**Comment by wfondrie** [comment]
I thing this is the way to go. It's probably not worth adding a `--global_max_train` option though. 

Want to put in a PR? If not, I can take care of it tomorrow.

**Comment by jspaezp** [comment]
@wfondrie sent the PR
