### ISSUE TITLE
[BUG] 'GridSearchCV' object has no attribute 'intercept_'

### ISSUE THREAD

**Issue by lazear** [wfondrie/mokapot#63]
**Describe the bug:**

Hi! I've been playing around with mokapot, but just hit a new error for the first time. Let me know if I can provide more info!

Stack trace:

```py
[INFO] mokapot version 0.8.1
[INFO] Written by William E. Fondrie (wfondrie@uw.edu) in the
[INFO] Department of Genome Sciences at the University of Washington.
[INFO] Command issued:
[INFO] $PATH\Scripts\mokapot results.pin --train_fdr 0.05 --test_fdr 0.05
[INFO]
[INFO] Starting Analysis
[INFO] =================
[INFO] Parsing PSMs...
[INFO] Reading results.pin...
[INFO] Using 8 features:
[INFO]   (1)    charge
[INFO]   (2)    rt
[INFO]   (3)    mass_error
[INFO]   (4)    hyperscore
[INFO]   (5)    deltascore
[INFO]   (6)    matched_peaks
[INFO]   (7)    total_candidates
[INFO]   (8)    q_value
[INFO] Found 20639 PSMs.
[INFO]   - 10361 target PSMs and 10278 decoy PSMs detected.
[INFO] Splitting PSMs into 3 folds...
[INFO] 
[INFO] === Analyzing Fold 1 ===
[INFO] Finding initial direction...
[INFO]  - Selected feature q_value with 328 PSMs at q<=0.05.
[INFO] Selecting hyperparameters...
[INFO]  - class_weight = {0: 10, 1: 10}
[INFO] Beginning training loop...
[INFO]  - Iteration 0: 331 training PSMs passed.
[INFO]  - Iteration 1: 333 training PSMs passed.
[INFO]  - Iteration 2: 362 training PSMs passed.
[INFO]  - Iteration 3: 381 training PSMs passed.
[INFO]  - Iteration 4: 389 training PSMs passed.
[INFO]  - Iteration 5: 390 training PSMs passed.
[INFO]  - Iteration 6: 389 training PSMs passed.
[INFO]  - Iteration 7: 389 training PSMs passed.
[INFO]  - Iteration 8: 389 training PSMs passed.
[INFO]  - Iteration 9: 389 training PSMs passed.
[INFO] Normalized feature weights in the learned model:
[INFO]     Feature           Weight
[INFO]     charge            0.315888185371381
[INFO]     rt                0.0
[INFO]     mass_error        -0.06702181783995004
[INFO]     hyperscore        0.012824732750116497
[INFO]     deltascore        -0.03721698905618377
[INFO]     matched_peaks     0.015238832942401782
[INFO]     total_candidates  -0.03444022897119131
[INFO]     q_value           -4.138678009462961
[INFO]     intercept         -7.1538355002957275
[INFO] Done training.
[INFO] 
[INFO] === Analyzing Fold 2 ===
[INFO] Finding initial direction...
[INFO]  - Selected feature q_value with 582 PSMs at q<=0.05.
[INFO] Selecting hyperparameters...
[INFO]  - class_weight = {0: 10, 1: 10}
[INFO] Beginning training loop...
[INFO]  - Iteration 0: 312 training PSMs passed.
[INFO]  - Iteration 1: 310 training PSMs passed.
[INFO]  - Iteration 2: 311 training PSMs passed.
[INFO]  - Iteration 3: 311 training PSMs passed.
[INFO]  - Iteration 4: 311 training PSMs passed.
[INFO]  - Iteration 5: 311 training PSMs passed.
[INFO]  - Iteration 6: 311 training PSMs passed.
[INFO]  - Iteration 7: 311 training PSMs passed.
[INFO]  - Iteration 8: 311 training PSMs passed.
[INFO]  - Iteration 9: 311 training PSMs passed.
[INFO]
[INFO] === Analyzing Fold 3 ===
[INFO] Finding initial direction...
[INFO]  - Selected feature q_value with 290 PSMs at q<=0.05.
[INFO] Selecting hyperparameters...
[INFO]  - class_weight = {0: 10, 1: 10}
[INFO] Beginning training loop...
[INFO]  - Iteration 0: 293 training PSMs passed.
[INFO]  - Iteration 1: 293 training PSMs passed.
[INFO]  - Iteration 2: 290 training PSMs passed.
[INFO]  - Iteration 3: 291 training PSMs passed.
[INFO]  - Iteration 4: 293 training PSMs passed.
[INFO]  - Iteration 5: 289 training PSMs passed.
[INFO]  - Iteration 6: 301 training PSMs passed.
[INFO]  - Iteration 7: 336 training PSMs passed.
[INFO]  - Iteration 8: 343 training PSMs passed.
[INFO]  - Iteration 9: 266 training PSMs passed.
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "$PATH\Scripts\mokapot.exe\__main__.py", line 7, in <module>
  File "$PATH\lib\site-packages\mokapot\mokapot.py", line 97, in main
    psms, models = brew(
  File "$PATH\lib\site-packages\mokapot\brew.py", line 124, in brew
    models.sort(key=lambda x: x[0].estimator.intercept_)
  File "$PATH\lib\site-packages\mokapot\brew.py", line 124, in <lambda>
    models.sort(key=lambda x: x[0].estimator.intercept_)
AttributeError: 'GridSearchCV' object has no attribute 'intercept_'
```

Dependencies (exported from poetry)
```
cycler==0.11.0; python_version >= "3.7"
fonttools==4.34.4; python_version >= "3.7"
joblib==1.1.0; python_version >= "3.8"
kiwisolver==1.4.4; python_version >= "3.7"
llvmlite==0.34.0; python_version >= "3.6"
lxml==4.9.1; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version >= "3.6"
matplotlib==3.5.2; python_version >= "3.7"
mokapot==0.8.1; python_version >= "3.6"
numba==0.51.2; python_version >= "3.6"
numpy==1.22.4
packaging==21.3; python_version >= "3.7"
pandas==1.4.3; python_version >= "3.8"
pillow==9.2.0; python_version >= "3.7"
pyparsing==3.0.9; python_full_version >= "3.6.8" and python_version >= "3.7"
python-dateutil==2.8.2; python_version >= "3.8" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" and python_version >= "3.8"
pytz==2022.1; python_version >= "3.8"
scikit-learn==1.1.1; python_version >= "3.8"
scipy==1.8.1; python_version >= "3.8" and python_version < "3.11"
seaborn==0.11.2; python_version >= "3.6"
setuptools-scm==7.0.5; python_version >= "3.7"
six==1.16.0; python_version >= "3.8" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" and python_version >= "3.8"
threadpoolctl==3.1.0; python_version >= "3.8"
tomli==2.0.1; python_version >= "3.7"
triqler==0.6.2; python_version >= "3.6"
typing-extensions==4.3.0; python_version >= "3.7"
```

**To Reproduce:**

Bug encountered while using mokapot from command line: `mokapot results.pin --train_fdr 0.05 --test_fdr 0.05`

**Comment by wfondrie** [comment]
Hi @lazear - this is a bug that we've almost finished fixing! Sorry that you ran into it. (See issue #61 and PR #62)

We should be rolling out the fix today, but if you need it sooner, my recommendation is rolling back to mokapot v0.8.0.

**Comment by lazear** [comment]
Perfect, thanks!

**Comment by wfondrie** [comment]
Version 0.8.2 is now available on PyPI 🎉 
It'll take a little bit for the release to be on Bioconda, but that should also be later today.

Please don't hesitate to re-open this issue if you upgrade and still have problems.
